apiVersion: v1alpha1
kind: Role
metadata:
  name: cooperation-manage
spec:
  displayName: 合作咨询管理
  rules:
    - apiGroups: ["api.cooperation.vivid.run"]
      resources: ["cooperations"]
      verbs: ["*"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: cooperation-view
spec:
  displayName: 合作咨询查看
  rules:
    - apiGroups: ["api.cooperation.vivid.run"]
      resources: ["cooperations"]
      verbs: ["get", "list"]
